_BASE_: "./k600_base.yaml"
MODEL:
  ACTION_LOSS: False
  FROZEN_BACKBONE: True
  FROZEN_ACTION_HEADER: True
  FROZEN_PASTAS: []
  FROZEN_VERB_CLASSIFIER: True
  K700_BACKBONE: False
  LOSS_FUNC: bce
  PASTA_CLASSIFIER: True
DATA_LOADER:
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.004
  MAX_EPOCH: 100
TENSORBOARD:
  ENABLE: True
TRAIN:
  DATASET: hake
  ENABLE: True
  PER_GPU_BS: 4
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: False
  FOCAL_GAMMA: 2.0
  VAL_ONLY: False
TEST:
  ENABLE: False
